### ISSUE TITLE
Add support for including images

### ISSUE THREAD

**Issue by omkarap55** [ognjen-petrovic/js-dxf#62]
Hi, 
any plans to add support for including images in DXF file?

**Comment by ognjen-petrovic** [comment]
Hi,

I have not had such a plan. I do not know how complicated would that be, do you have the idea?

**Comment by omkarap55** [comment]
Actually, I do not have any idea about the level of complexity of this feature.
I have seen this feature in [LibreCAD](https://librecad.org/). Maybe this could be useful reference for you.
Let me know your thoughts.

**Comment by tarikjabiri** [comment]
Hi, 

After some research the js-dxf need a dynamic API for managing sections.
In order to implementing an IMAGE entity we need tow objects in OBJECTS section IMAGEDEF and IMAGEDEF_REACTOR and I think we need a class in CLASSES section.
I am curently aiming to implementig this feature but I am strugling with DXF reference, also finding a good algorithm for the current api.

**Comment by Kinatzo** [comment]
I'm also very intersted in being able to add raster images!

**Comment by SinMayFly** [comment]
Hi, now i have problems, how to fill the color for the graphics, and  my English is bad ,sry

**Comment by novotechsoft** [comment]
> Hi,
> 
> After some research the js-dxf need a dynamic API for managing sections. In order to implement an IMAGE entity we need tow objects in OBJECTS section IMAGEDEF and IMAGEDEF_REACTOR and I think we need a class in CLASSES section. I am curently aiming to implementig this feature but I am strugling with DXF reference, also finding a good algorithm for the current api.

hi, I see that you added image support for your TypeScript library. Can we add the same here for js-dxf?

**Comment by tarikjabiri** [comment]
Hi,
@ognjen-petrovic said to keep js-dxf simple as possible so implementing Image entity is a bit tricky because needs objects to be implemented.

I am working on my lib so the next version support as many features as possible but I am struggling with time(I am not free) and the dxf spec.
And about hatch I will see if can implement  it

**Comment by novotechsoft** [comment]
thanks very much! Hatch is a very vital part of DXF or DWG files, so adding it to js-dxf will be a great step ahead. Thank you again for the quick reply.

**Comment by tarikjabiri** [comment]
Hi,

The `HATCH`, `IMAGE`, `INSERT` and `BLOCKS` are implemented in my lib, and I published a pre-release see [NPM](https://www.npmjs.com/package/@tarikjabiri/dxf/v/2.0.0-rc) or [Github](https://github.com/tarikjabiri/dxf/releases/tag/v2.0.0-rc).
For more informations see [Documantation](https://tarikjabiri.github.io/dxf/docs/).

And I want to say sorry I can't implent them in ***js-dxf*** because focusing in tow libs is hard for me, I will add features that are easy to implement.

Thank you.
